/* {{NAME}} — generated by Forge */
const COLLECTION = '{{COLLECTION}}';
const FIELDS = {{FIELDS}};
// Resolves correctly in both deployment shapes: standalone (served at /) and embedded
// under Forge's preview proxy (/generated/<slug>/…).
const BASE = (() => {
  const marker = '/generated/';
  const at = window.location.pathname.indexOf(marker);
  if (at === -1) return '';
  return marker + window.location.pathname.slice(at + marker.length).split('/')[0];
})();
const API = `${BASE}/api/${COLLECTION}`;

const $ = (id) => document.getElementById(id);
const state = { items: [], total: 0, query: {}, editing: null, sort: { field: '{{SORT_FIELD}}', dir: 'desc' } };

/* ------------------------------------------------------------------ utils */

const fmt = (value, field) => {
  if (value === null || value === undefined || value === '') return '—';
  if (field.type === 'number' || field.type === 'currency') {
    const n = Number(value);
    if (!Number.isFinite(n)) return String(value);
    return field.type === 'currency'
      ? n.toLocaleString(undefined, { style: 'currency', currency: '{{CURRENCY}}', maximumFractionDigits: 2 })
      : n.toLocaleString();
  }
  if (field.type === 'date') {
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
  }
  if (field.type === 'boolean') return value === true || value === 'true' ? 'Yes' : 'No';
  return String(value);
};

const toast = (message, kind = 'ok') => {
  const el = $('toast');
  el.textContent = message;
  el.dataset.kind = kind;
  el.hidden = false;
  clearTimeout(toast.timer);
  toast.timer = setTimeout(() => { el.hidden = true; }, 2600);
};

async function api(path = '', options = {}) {
  const res = await fetch(`${API}${path}`, {
    headers: { 'content-type': 'application/json' },
    ...options,
    body: options.body ? JSON.stringify(options.body) : undefined,
  });
  const text = await res.text();
  let payload;
  try { payload = text ? JSON.parse(text) : {}; } catch { payload = { raw: text }; }
  if (!res.ok) throw Object.assign(new Error(payload.detail || payload.error || `HTTP ${res.status}`), { status: res.status, payload });
  return payload;
}

/* ------------------------------------------------------------------ boot */

function buildControls() {
  const filterField = $('filter-field');
  const sortField = $('sort-field');
  filterField.innerHTML = '<option value="">none</option>' + FIELDS.map((f) => `<option value="${f.name}">${f.label}</option>`).join('');
  sortField.innerHTML = FIELDS.map((f) => `<option value="${f.name}">${f.label}</option>`).join('');
  sortField.value = state.sort.field;
  filterField.addEventListener('change', async () => {
    const field = FIELDS.find((f) => f.name === filterField.value);
    const valueSelect = $('filter-value');
    if (!field) { valueSelect.innerHTML = '<option value="">any</option>'; return; }
    const values = [...new Set(state.items.map((r) => r[field.name]).filter((v) => v !== null && v !== undefined && v !== ''))].sort();
    valueSelect.innerHTML = '<option value="">any</option>' + values.map((v) => `<option value="${String(v)}">${String(v)}</option>`).join('');
  });
  $('sort-field').addEventListener('change', () => { state.sort.field = $('sort-field').value; load(); });
  $('sort-dir').addEventListener('click', (e) => {
    state.sort.dir = state.sort.dir === 'asc' ? 'desc' : 'asc';
    e.currentTarget.textContent = state.sort.dir === 'asc' ? '↑ Asc' : '↓ Desc';
    load();
  });
  let debounce;
  $('search').addEventListener('input', (e) => {
    clearTimeout(debounce);
    debounce = setTimeout(() => { state.query.q = e.target.value.trim(); load(); }, 180);
  });
  $('filter-value').addEventListener('change', () => {
    const field = $('filter-field').value;
    const value = $('filter-value').value;
    state.query = { q: state.query.q || '' };
    if (field && value) state.query[field] = value;
    load();
  });
  $('new-btn').addEventListener('click', () => openForm(null));
  $('export-btn').addEventListener('click', () => {
    const qs = new URLSearchParams({ ...state.query, sort: state.sort.field, dir: state.sort.dir }).toString();
    window.location.href = `${API}/export.csv?${qs}`;
  });
}

function renderHead() {
  const row = $('head-row');
  row.innerHTML = FIELDS.map((f) => `<th scope="col">${f.label}</th>`).join('') + '<th scope="col" class="actions-col">Actions</th>';
}

function renderRows(items) {
  const body = $('body');
  $('empty').hidden = items.length > 0;
  body.innerHTML = items
    .map(
      (row) => `<tr data-id="${row.id}">${FIELDS.map((f) => {
        const value = row[f.name];
        const badge = f.type === 'select' || f.type === 'boolean' ? ` data-badge="${String(value)}"` : '';
        return `<td${badge}>${escapeHtml(fmt(value, f))}</td>`;
      }).join('')}<td class="actions-col">
        <button class="btn tiny" data-action="edit" data-id="${row.id}" type="button">Edit</button>
        <button class="btn tiny danger" data-action="delete" data-id="${row.id}" type="button">Delete</button>
      </td></tr>`,
    )
    .join('');
}

const escapeHtml = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function renderStats(stats) {
  const cards = [];
  cards.push(`<div class="card"><span class="card-label">Total ${escapeHtml(COLLECTION)}</span><strong class="card-value">${stats.total.toLocaleString()}</strong><span class="card-foot">records stored</span></div>`);
  for (const [field, s] of Object.entries(stats.numeric)) {
    const meta = FIELDS.find((f) => f.name === field) || { label: field, type: 'number' };
    if (!s.count) continue;
    const primary = meta.type === 'currency' ? fmt(s.sum, meta) : fmt(s.mean, meta);
    cards.push(`<div class="card"><span class="card-label">${escapeHtml(meta.label)} ${meta.type === 'currency' ? 'total' : 'mean'}</span><strong class="card-value">${primary}</strong><span class="card-foot">min ${fmt(s.min, meta)} · max ${fmt(s.max, meta)} · n=${s.count}</span></div>`);
  }
  for (const [field, groups] of Object.entries(stats.groups)) {
    const meta = FIELDS.find((f) => f.name === field) || { label: field };
    const top = groups.slice(0, 3).map((g) => `${escapeHtml(g.value)} (${g.count})`).join(' · ');
    cards.push(`<div class="card wide"><span class="card-label">${escapeHtml(meta.label)} breakdown</span><strong class="card-value small">${top}</strong><span class="card-foot">${groups.length} distinct value(s)</span></div>`);
  }
  $('stats').innerHTML = cards.join('');
}

/* ------------------------------------------------------------------- crud */

function openForm(item) {
  state.editing = item;
  $('dialog-title').textContent = item ? `Edit ${TITLE_FIELD_LABEL}` : 'New {{SINGULAR_LABEL}}';
  $('form-error').hidden = true;
  $('form-fields').innerHTML = FIELDS.map((f) => {
    const value = item ? item[f.name] : '';
    const required = f.required ? 'required' : '';
    if (f.type === 'select') {
      const options = ['', ...(f.options || [])].map((o) => `<option value="${o}"${String(value) === String(o) ? ' selected' : ''}>${o || '—'}</option>`).join('');
      return `<label class="form-field"><span>${f.label}${f.required ? ' *' : ''}</span><select name="${f.name}" ${required}>${options}</select></label>`;
    }
    if (f.type === 'boolean') {
      return `<label class="form-field check"><input type="checkbox" name="${f.name}" ${value === true || value === 'true' ? 'checked' : ''} /><span>${f.label}</span></label>`;
    }
    const type = f.type === 'number' || f.type === 'currency' ? 'number' : f.type === 'date' ? 'date' : 'text';
    const step = f.type === 'number' || f.type === 'currency' ? ' step="any"' : '';
    const val = f.type === 'date' && value ? String(value).slice(0, 10) : value ?? '';
    return `<label class="form-field"><span>${f.label}${f.required ? ' *' : ''}</span><input type="${type}" name="${f.name}" value="${escapeHtml(val)}"${step} ${required} /></label>`;
  }).join('');
  $('dialog').showModal();
  const first = $('dialog').querySelector('input,select');
  if (first) first.focus();
}

async function save(event) {
  event.preventDefault();
  const submitter = event.submitter;
  if (submitter && submitter.value === 'cancel') { $('dialog').close(); return; }
  const data = {};
  for (const f of FIELDS) {
    const el = $('form').elements[f.name];
    if (!el) continue;
    if (f.type === 'boolean') data[f.name] = el.checked;
    else data[f.name] = el.value === '' ? null : el.value;
  }
  try {
    if (state.editing) {
      await api(`/${state.editing.id}`, { method: 'PATCH', body: data });
      toast('Saved');
    } else {
      await api('', { method: 'POST', body: data });
      toast('Created');
    }
    $('dialog').close();
    await load();
  } catch (err) {
    const detail = err.payload?.errors ? err.payload.errors.join('; ') : err.message;
    const box = $('form-error');
    box.textContent = detail;
    box.hidden = false;
  }
}

async function remove(id) {
  if (!confirm('Delete this record? This cannot be undone.')) return;
  try {
    await api(`/${id}`, { method: 'DELETE' });
    toast('Deleted');
    await load();
  } catch (err) {
    toast(err.message, 'error');
  }
}

/* ------------------------------------------------------------------- load */

async function load() {
  const params = new URLSearchParams({ ...state.query, sort: state.sort.field, dir: state.sort.dir });
  for (const [k, v] of [...params.entries()]) if (!v) params.delete(k);
  const [list, stats] = await Promise.all([api(`?${params.toString()}`), api('/stats')]);
  state.items = list.items;
  state.total = list.total;
  renderRows(list.items);
  renderStats(stats);
  $('count').textContent = `${list.total} of ${stats.total} record${stats.total === 1 ? '' : 's'}`;
}

async function ping() {
  try {
    const res = await fetch(`${API}/health`);
    const data = await res.json();
    $('health').textContent = `live · ${data.records} record(s)`;
    $('health').dataset.state = 'ok';
  } catch {
    $('health').textContent = 'offline';
    $('health').dataset.state = 'down';
  }
}

document.addEventListener('click', (event) => {
  const target = event.target.closest('button[data-action]');
  if (!target) return;
  const { action, id } = target.dataset;
  const item = state.items.find((r) => r.id === id);
  if (action === 'edit' && item) openForm(item);
  if (action === 'delete') remove(id);
});

$('form').addEventListener('submit', save);

buildControls();
renderHead();
await ping();
await load();
setInterval(ping, 15000);
