# {{NAME}}

{{DESCRIPTION}}

Built from a plain-English description by **Forge** — no manual code. Everything here is
ordinary, editable source: change it, keep it, or regenerate.

## Run it

```bash
node server.js            # http://localhost:{{PORT}}
# or
npm start
```

No dependencies. Node 20+ is the only requirement (`node --version`).

## Test it

```bash
npm test                  # node:test — 12 real HTTP tests
```

The suite boots the actual server on an ephemeral port with a throwaway data file, then
exercises create / read / update / delete, validation, search, stats, CSV export, 404s
and the path-traversal guard. If `npm test` is green, the API really works.

## What it does

| Feature | Where |
| --- | --- |
| CRUD over HTTP with JSON | `server.js` → `/api/{{COLLECTION}}` |
| Validation with field-level errors (422) | `validate()` in `server.js` |
| Search, filtering, sorting, pagination | query string: `?q=&sort=&dir=&limit=&offset=` |
| Aggregates (sum / mean / min / max + breakdowns) | `GET /api/{{COLLECTION}}/stats` |
| CSV export of the current filter | `GET /api/{{COLLECTION}}/export.csv` |
| Persistence (atomic JSON writes) | `data/{{COLLECTION}}.json` |
| Live dashboard, no build step | `public/index.html` + `public/app.js` |

## Data model

| Field | Type | Required |
| --- | --- | --- |
{{FIELD_TABLE}}

Records also carry `id`, `createdAt` and `updatedAt`, which the server manages — you
cannot set them by hand.

## API

```
GET    /api/health                     → { status, collection, records }
GET    /api/{{COLLECTION}}                   → { total, limit, offset, items }
POST   /api/{{COLLECTION}}                   → 201 created record
GET    /api/{{COLLECTION}}/:id               → single record
PATCH  /api/{{COLLECTION}}/:id               → partial update
PUT    /api/{{COLLECTION}}/:id               → full update
DELETE /api/{{COLLECTION}}/:id               → { deleted: id }
GET    /api/{{COLLECTION}}/stats             → aggregates
GET    /api/{{COLLECTION}}/export.csv        → CSV of the filtered set
```

```bash
curl -X POST localhost:{{PORT}}/api/{{COLLECTION}} \
  -H 'content-type: application/json' \
  -d '{{CURL_EXAMPLE}}'
```

## Deployment

The server binds `0.0.0.0:$PORT`, so any container host works as-is:

```dockerfile
FROM node:22-alpine
WORKDIR /app
COPY . .
ENV PORT=3000
CMD ["node", "server.js"]
```

## Notes and limits

{{LIMITS}}

---
Generated by Forge · {{GENERATED_AT}}
