// name: {{NAME}}
// description: {{DESCRIPTION}}
// Generated by Forge. Zero-dependency Node service — `node server.js` and it runs.
import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, 'public');
const DATA_DIR = path.join(__dirname, 'data');
// FORGE_DATA_FILE lets the test suite point at a throwaway store.
const DATA_FILE = process.env.FORGE_DATA_FILE || path.join(DATA_DIR, '{{COLLECTION}}.json');
const PORT = Number(process.env.PORT || {{PORT}});

const COLLECTION = '{{COLLECTION}}';
const TITLE_FIELD = '{{TITLE_FIELD}}';
{{VALIDATION}}
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
};

/* ------------------------------------------------------------------ store */

let rows = [];
let writeQueue = Promise.resolve();

export async function load() {
  await fsp.mkdir(DATA_DIR, { recursive: true });
  try {
    rows = JSON.parse(await fsp.readFile(DATA_FILE, 'utf8'));
    if (!Array.isArray(rows)) rows = [];
  } catch {
    rows = [];
    await persist();
  }
}

function persist() {
  // Serialised writes: no interleaving, no half-written file.
  writeQueue = writeQueue.then(async () => {
    const tmp = `${DATA_FILE}.tmp`;
    await fsp.writeFile(tmp, JSON.stringify(rows, null, 2));
    await fsp.rename(tmp, DATA_FILE);
  });
  return writeQueue;
}

const nextId = () => (rows.reduce((max, r) => Math.max(max, Number(String(r.id).replace(/\D/g, '')) || 0), 0) + 1).toString().padStart(4, '0');

/* -------------------------------------------------------------- helpers */

const json = (res, status, payload) => {
  const body = JSON.stringify(payload);
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(body),
    'cache-control': 'no-store',
  });
  res.end(body);
};

const readBody = (req, limit = 1_000_000) =>
  new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on('data', (chunk) => {
      size += chunk.length;
      if (size > limit) {
        reject(Object.assign(new Error('payload too large'), { status: 413 }));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch {
        reject(Object.assign(new Error('body must be valid JSON'), { status: 400 }));
      }
    });
    req.on('error', reject);
  });

const csvCell = (value) => {
  const s = value === null || value === undefined ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

function applyQuery(list, params) {
  let out = [...list];
  const q = (params.get('q') || '').trim().toLowerCase();
  if (q) {
    out = out.filter((row) =>
      Object.values(row).some((v) => String(v ?? '').toLowerCase().includes(q)),
    );
  }
  for (const [key, value] of params.entries()) {
    if (['q', 'sort', 'dir', 'limit', 'offset', 'page'].includes(key)) continue;
    if (value === '' || value == null) continue;
    out = out.filter((row) => String(row[key] ?? '').toLowerCase() === value.toLowerCase());
  }
  const sort = params.get('sort');
  const dir = params.get('dir') === 'desc' ? -1 : 1;
  if (sort) {
    out.sort((a, b) => {
      const [x, y] = [a[sort], b[sort]];
      if (typeof x === 'number' && typeof y === 'number') return (x - y) * dir;
      return String(x ?? '').localeCompare(String(y ?? ''), undefined, { numeric: true }) * dir;
    });
  }
  return out;
}

function stats(list) {
  const numeric = {{NUMERIC_FIELDS}};
  const byField = {};
  for (const field of numeric) {
    // Coerce only real values: Number(null) is 0, which would silently skew min/mean.
    const values = list
      .map((r) => r[field])
      .filter((v) => v !== null && v !== undefined && v !== '')
      .map(Number)
      .filter((n) => Number.isFinite(n));
    byField[field] = values.length
      ? {
          count: values.length,
          sum: Number(values.reduce((a, b) => a + b, 0).toFixed(2)),
          mean: Number((values.reduce((a, b) => a + b, 0) / values.length).toFixed(2)),
          min: Math.min(...values),
          max: Math.max(...values),
        }
      : { count: 0, sum: 0, mean: 0, min: null, max: null };
  }
  const groupFields = {{GROUP_FIELDS}};
  const groups = {};
  for (const field of groupFields) {
    const counts = {};
    for (const row of list) {
      const key = String(row[field] ?? '—');
      counts[key] = (counts[key] || 0) + 1;
    }
    groups[field] = Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([value, count]) => ({ value, count }));
  }
  return { total: list.length, numeric: byField, groups, updatedAt: new Date().toISOString() };
}

/* ------------------------------------------------------------------ api */

async function handleApi(req, res, url) {
  const parts = url.pathname.split('/').filter(Boolean); // ['api', COLLECTION, ...rest]
  if (parts[1] !== COLLECTION) return json(res, 404, { error: 'not_found', detail: `no collection named "${parts[1] ?? ''}"` });
  const rest = parts.slice(2);

  if (rest[0] === 'stats' && req.method === 'GET') return json(res, 200, stats(rows));
  if (rest[0] === 'export.csv' && req.method === 'GET') {
    const fields = FIELDS.map((f) => f.name);
    const list = applyQuery(rows, url.searchParams);
    const csv = [fields.join(','), ...list.map((row) => fields.map((f) => csvCell(row[f])).join(','))].join('\n');
    res.writeHead(200, { 'content-type': 'text/csv; charset=utf-8', 'content-disposition': `attachment; filename="${COLLECTION}.csv"` });
    return res.end(csv);
  }

  const id = rest[0];
  if (req.method === 'GET' && id) {
    const row = rows.find((r) => r.id === id);
    if (!row) return json(res, 404, { error: 'not_found', detail: `${COLLECTION} ${id} does not exist` });
    return json(res, 200, row);
  }

  if (req.method === 'GET') {
    const filtered = applyQuery(rows, url.searchParams);
    const limit = Math.min(Number(url.searchParams.get('limit') || 200), 1000);
    const offset = Math.max(Number(url.searchParams.get('offset') || 0), 0);
    return json(res, 200, {
      total: filtered.length,
      limit,
      offset,
      items: filtered.slice(offset, offset + limit),
    });
  }

  if (req.method === 'POST') {
    const body = await readBody(req);
    const { value, errors } = validate(body);
    if (errors.length) return json(res, 422, { error: 'validation_failed', errors });
    const now = new Date().toISOString();
    const row = { id: nextId(), ...value, createdAt: now, updatedAt: now };
    rows.push(row);
    await persist();
    return json(res, 201, row);
  }

  if (req.method === 'PATCH' || req.method === 'PUT') {
    const row = rows.find((r) => r.id === id);
    if (!row) return json(res, 404, { error: 'not_found', detail: `${COLLECTION} ${id} does not exist` });
    const body = await readBody(req);
    const { value, errors } = validate(body, { partial: req.method === 'PATCH' });
    if (errors.length) return json(res, 422, { error: 'validation_failed', errors });
    Object.assign(row, value, { updatedAt: new Date().toISOString() });
    await persist();
    return json(res, 200, row);
  }

  if (req.method === 'DELETE') {
    const index = rows.findIndex((r) => r.id === id);
    if (index === -1) return json(res, 404, { error: 'not_found', detail: `${COLLECTION} ${id} does not exist` });
    const [removed] = rows.splice(index, 1);
    await persist();
    return json(res, 200, { deleted: removed.id });
  }

  return json(res, 405, { error: 'method_not_allowed', allow: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'] });
}

/* --------------------------------------------------------------- static */

async function serveStatic(req, res, url) {
  const rel = url.pathname === '/' || url.pathname === '' ? 'index.html' : url.pathname.replace(/^\/+/, '');
  const resolved = path.join(PUBLIC_DIR, rel);
  if (!resolved.startsWith(PUBLIC_DIR)) return json(res, 403, { error: 'forbidden' }); // path traversal guard
  try {
    const data = await fsp.readFile(resolved);
    res.writeHead(200, { 'content-type': MIME[path.extname(resolved)] || 'application/octet-stream', 'cache-control': 'no-cache' });
    return res.end(data);
  } catch {
    try {
      const html = await fsp.readFile(path.join(PUBLIC_DIR, 'index.html'));
      res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
      return res.end(html);
    } catch {
      return json(res, 404, { error: 'not_found', detail: `${url.pathname} not found` });
    }
  }
}

export function createServer() {
  return http.createServer(async (req, res) => {
    const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
    try {
      if (url.pathname === '/api/health') return json(res, 200, { status: 'ok', collection: COLLECTION, records: rows.length, uptimeSeconds: Math.round(process.uptime()) });
      if (url.pathname.startsWith('/api/')) return await handleApi(req, res, url);
      return await serveStatic(req, res, url);
    } catch (err) {
      const status = err.status || 500;
      if (status >= 500) console.error('[app]', err);
      return json(res, status, { error: status === 500 ? 'internal_error' : 'request_error', detail: err.message });
    }
  });
}

if (process.env.NODE_ENV !== 'test') {
  await load();
  const server = createServer();
  server.listen(PORT, '0.0.0.0', () => {
    console.log(`{{NAME}} listening on http://0.0.0.0:${PORT}  (${rows.length} ${COLLECTION} loaded)`);
  });
}
